#!/bin/bash

echo $1
echo ${BASH_SOURCE%/*}

filename=cb_2018_us_state_5m

rm -rvf build
mkdir -p build

# Download and unzip the shape files
curl -o ${BASH_SOURCE%/*}/${filename}.zip -L https://www2.census.gov/geo/tiger/GENZ2018/shp/${filename}.zip
unzip -od build ${BASH_SOURCE%/*}/${filename}.zip
chmod a-x build/${filename}.*

# Convert to GeoJSON
shp2json build/${filename}.shp -o build/${filename}.geo.json

# Extract only relevant geospatial features and their properties (e.g., names)
process_d="
{ GEOID } = d.properties,
d.id = GEOID,
d"

cat build/${filename}.geo.json | \
ndjson-split 'd.features' | \
ndjson-map "$process_d" > build/${filename}.ndjson

# Convert to compressed topojson
geo2topo -n states=build/${filename}.ndjson | \
# toposimplify -p 0.03 -f | \
topoquantize 1e5  > ${BASH_SOURCE%/*}/${filename}.json
